# Generated by Django 4.2.25 on 2025-10-30 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_vehicule",
                    models.CharField(
                        choices=[("voiture", "Voiture"), ("moto", "Moto")],
                        max_length=20,
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("annee", models.IntegerField()),
                ("immatriculation", models.CharField(max_length=20, unique=True)),
                (
                    "prix_journalier",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("cylindree", models.IntegerField(blank=True, null=True)),
                ("nombre_portes", models.IntegerField(blank=True, null=True)),
                ("disponible", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "nb_jours",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("termine", "Terminé"),
                            ("en_retard", "En retard"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("carte", "Carte bancaire"),
                            ("virement", "Virement"),
                            ("especes", "Espèces"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("details_paiement", models.JSONField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestion.client"
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.vehicule",
                    ),
                ),
            ],
        ),
    ]
