# Generated by Django 4.2.7 on 2025-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_contract_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="contrat",
            options={"verbose_name": "Contrat", "verbose_name_plural": "Contrats"},
        ),
        migrations.AlterModelOptions(
            name="vehicule",
            options={"verbose_name": "Véhicule", "verbose_name_plural": "Véhicules"},
        ),
        migrations.RemoveField(
            model_name="contrat",
            name="date_rupture",
        ),
        migrations.RemoveField(
            model_name="contrat",
            name="frais_rupture",
        ),
        migrations.RemoveField(
            model_name="contrat",
            name="motif_rupture",
        ),
        migrations.RemoveField(
            model_name="vehicule",
            name="date_derniere_maintenance",
        ),
        migrations.RemoveField(
            model_name="vehicule",
            name="kilometrage",
        ),
        migrations.RemoveField(
            model_name="vehicule",
            name="prochaine_maintenance",
        ),
        migrations.AlterField(
            model_name="contrat",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carte", "Carte bancaire"),
                    ("virement", "Virement"),
                    ("especes", "Espèces"),
                    ("cheque", "Chèque"),
                    ("mobile", "Paiement mobile"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("termine", "Terminé"),
                    ("en_retard", "En retard"),
                    ("rompu", "Rompu"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
    ]
