# Generated by Django 4.2.7 on 2025-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_alter_client_options_alter_contrat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicule",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicules/"),
        ),
    ]
