# Generated by Django 4.2.7 on 2025-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_vehicule_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=150, null=True)),
                ("model", models.CharField(max_length=150)),
                ("object_id", models.CharField(max_length=150)),
                ("action", models.CharField(max_length=50)),
                ("changes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
