# Generated by Django 4.2.7 on 2025-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("carte", "Carte bancaire"),
                    ("virement", "Virement"),
                    ("especes", "Espèces"),
                    ("cheque", "Chèque"),
                    ("mobile", "Paiement mobile"),
                ],
                default="especes",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="montant_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
